# Sets up a development container 
# and starts the development server

FROM ghcr.io/empiricaly/empirica:build-249

# jq for parsing javascript (tajriba.json)
# RUN apt-get update && \
#   apt-get install -q -y --no-install-recommends \
#     jq \
#   && apt-get clean autoclean && \
#   apt-get autoremove --yes && \
#   rm -rf /var/lib/{apt,dpkg,cache,log}/

WORKDIR /build

# ENTRYPOINT ["tail", "-f", "/dev/null"]

ADD ./deliberation-video-coding /build

# RUN echo $'[default] \n\
# aws_access_key_id = "$AWS_ACCESS_KEY_ID" \n\
# aws_secret_access_key = "$AWS_SECRET_ACCESS_KEY" \n\
# ' > /.aws/credentials

# install client dependencies
WORKDIR /build/client
#RUN npm install
RUN empirica npm install

## install server dependencies
WORKDIR /build/server
#RUN npm install
RUN empirica npm install

WORKDIR /build



# By default, the ghcr.io/empiricaly/empirica image will run empirica
